-- MySQL Script generated by MySQL Workbench
-- Tue May 18 18:02:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projek_smbd_inventaris
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projek_smbd_inventaris
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projek_smbd_inventaris` DEFAULT CHARACTER SET utf8 ;
USE `projek_smbd_inventaris` ;

-- -----------------------------------------------------
-- Table `projek_smbd_inventaris`.`anggota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projek_smbd_inventaris`.`anggota` (
  `nim` VARCHAR(32) NOT NULL,
  `nama_anggota` VARCHAR(128) NOT NULL,
  `jenis_kelamin_anggota` ENUM("L", "P") NOT NULL,
  `tgl_lahir_anggota` DATE NULL,
  `no_tlp_anggota` VARCHAR(15) NOT NULL,
  `alamat_anggota` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`nim`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projek_smbd_inventaris`.`petugas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projek_smbd_inventaris`.`petugas` (
  `id_petugas` INT NOT NULL AUTO_INCREMENT,
  `nama_petugas` VARCHAR(128) NOT NULL,
  `jenis_kelamin_petugas` ENUM("L", "P") NOT NULL,
  `tgl_lahir_petugas` DATE NULL,
  `no_tlp_petugas` VARCHAR(15) NULL,
  `alamat_petugas` VARCHAR(128) NOT NULL,
  `username_petugas` VARCHAR(128) NULL,
  `password_petugas` VARCHAR(128) NULL,
  PRIMARY KEY (`id_petugas`),
  UNIQUE INDEX `username_petugas_UNIQUE` (`username_petugas` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projek_smbd_inventaris`.`barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projek_smbd_inventaris`.`barang` (
  `id_barang` INT NOT NULL AUTO_INCREMENT,
  `nama_barang` VARCHAR(128) NOT NULL,
  `merk_barang` VARCHAR(128) NULL,
  `jumlah_barang` INT NOT NULL,
  `kondisi_barang` VARCHAR(128) NULL,
  `tgl_barang_masuk` DATE NOT NULL,
  PRIMARY KEY (`id_barang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projek_smbd_inventaris`.`peminjaman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projek_smbd_inventaris`.`peminjaman` (
  `id_peminjaman` INT NOT NULL AUTO_INCREMENT,
  `tgl_peminjaman` DATE NOT NULL,
  `tgl_kembali` DATE NULL,
  `denda` INT NULL,
  `petugas_id_petugas` INT NOT NULL,
  `barang_id_barang` INT NOT NULL,
  `anggota_nim` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_peminjaman`),
  INDEX `fk_peminjaman_petugas_idx` (`petugas_id_petugas` ) ,
  INDEX `fk_peminjaman_barang1_idx` (`barang_id_barang` ) ,
  INDEX `fk_peminjaman_anggota1_idx` (`anggota_nim` ) ,
  CONSTRAINT `fk_peminjaman_petugas`
    FOREIGN KEY (`petugas_id_petugas`)
    REFERENCES `projek_smbd_inventaris`.`petugas` (`id_petugas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peminjaman_barang1`
    FOREIGN KEY (`barang_id_barang`)
    REFERENCES `projek_smbd_inventaris`.`barang` (`id_barang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peminjaman_anggota1`
    FOREIGN KEY (`anggota_nim`)
    REFERENCES `projek_smbd_inventaris`.`anggota` (`nim`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projek_smbd_inventaris`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projek_smbd_inventaris`.`log` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `tipe_log` VARCHAR(128) NULL,
  `nama_tabel` VARCHAR(128) NULL,
  `id_tabel` VARCHAR(128) NULL,
  `waktu_log` DATETIME NULL,
  `user_petugas` VARCHAR(128) NULL,
  PRIMARY KEY (`id_log`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
